version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: php_hello_world_web
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    build: .
    container_name: php_hello_world_php
    volumes:
      - .:/var/www/html
